# Generated by Django 3.2.21 on 2023-09-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20230923_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='infocategory',
            name='description',
            field=models.TextField(default='Category description'),
        ),
    ]
