# Generated by Django 3.2.21 on 2023-09-23 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_faq_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='infocategory',
            name='faqs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='about.faq'),
        ),
    ]
