# Generated by Django 4.2.4 on 2023-08-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='on_sale',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
