# Generated by Django 3.2.21 on 2023-09-30 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_out_of_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='out_of_stock',
        ),
    ]
